Added index.php and created class Task.php in classes directory
htmlacademy-yii/796623-task-force-1 pull request #2
Opened 2020-08-20 09:35 UTC by likable

2020-08-22 07:53 UTC, denis-khodakovskiy requested changes

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +    const MAP_OF_THE_STATUSES = [
Имена переменных, констант, методов, классов и тд лучше сокращать. Не в том плане, что слова писать не полностью, а наоборот, писать слова без сокращений, но использовать как можно меньший их набор, при этом сохраняя в имени суть переменной, метода и тд. Поэтому предлагаю сделать так:
`MAP_OF_THE_STATUSES` -> `STATUSES_MAP`
`MAP_OF_THE_ACTIONS` -> `ACTIONS_MAP`

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +        'failed' => 'провалено'
1. У тебя уже есть в классе константы, со значениями, которые ты используешь в качестве ключей. Тут лучше их и использовать
```
self::STATUS_NEW => 'новое',
self::STATUS_CANCELLED => 'отменено',
...
```

2. Старайся не использовать в именах ключей пробелы. Лучше писать их в `camelCase` нотации
`in work` -> `inWork`

3. Последний элемент массива всегда должен иметь в конце запятую (если в массиве более 1 элемента)

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +
Оставляешь много пустых строк.
Так лучше не делать. Если надо отделить один логический блок кода от другого, то можно использовать одну пустую строку. Более одной оставлять не стоит

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +    private $customer_id; //заказчик
Будет время - найти в интернете стандарты PSR-12. Это стандарт о форматировании кода. Он требует, чтобы имена переменных, свойств, методов и тд писались в `camelCase` нотации
`customer_id` -> `customerId`

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +    public function getMapOfTheStatuses()
1. `getMapOfTheStatuses` -> `getStatusesMap`
2. Привыкай всегда сразу добавлять аннотации к методам и свойствам. К методам надо ещё добавлять тип данных, которые они возвращают
```
/** @return array */
public function getMapOfTheStatuses(): array
```

2020-08-22 07:53 UTC, denis-khodakovskiy commented on classes/Task.php
> +        switch ($action) {
Вместо `switch` лучше использовать массив константу, описанную в начале класса
```
const NEXT_STATUS_MAP = [
    self::ACTION_CANCEL => self::STATUS_CANCELLED,
    ...
];
```
и использовать этот массив в этом методе:
```
return self::NEXT_STATUS_MAP[$action];
```

2020-08-26 10:27 UTC, andrewverner requested changes

2020-08-26 10:27 UTC, andrewverner commented on classes/Task.php
> +        self::STATUS_FAILED => [],
Не думаю, что стоит вносить сюда статусы без действий. Если статусов без доступных действий будет 20, то массив будет содержать 20 пустых записей, которые не будут использоваться, но будут занимать память. Проще убрать их отсюда, а в методе, который возвращает доступные действия по статусу, сначала проверять, есть ли статус в списке ключей и, если нет, то возвращать пустой массив

2020-08-26 10:27 UTC, andrewverner commented on classes/Task.php
> +    const ACTION_CANCEL = 'actionCancel';
Константы лучше не "лепить" одну к другой.
Разбей их на группы
```
...
const STATUS_COMPLETED = 'completed';
const STATUS_FAILED = 'failed';

const ACTION_CANCEL = 'actionCancel';
const ACTION_IN_WORK = 'actionInWork';
...
```

2020-08-26 21:21 UTC, andrewverner requested changes

2020-08-26 21:21 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +        return '';
1. Это можно описать гораздо проще. В PHP есть оператор `??`. Запись
` return $array[$key] ?? false;`
равнозначна такой:
```
if (isset($array[$key]) {
    return $array[$key];
} else {
    return false;
} 
```
То есть всё это можно сократить до
```
return self::NEXT_STATUS_MAP[$action] ?? null;
```

2. Возврат пустых строк - плохая практика. Лучше вернуть `false` или `null`

2020-08-26 21:21 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +        return [];
Аналогично

2020-08-26 22:56 UTC, likable commented on src/BusinessLogic/Task.php
> +        return '';
Точно! Забыл про него. )
А если функция может возвращать не только строку, а ещё и null/false, то нужно ли указывать в качестве возвращаемого значения string?

2020-08-27 05:16 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +        return '';
В таких случаях возвращают либо string, либо null. В аннотации пишут так
`@return string|null`,
у метода так:
`public function myFunction(): ?string`

2020-08-27 05:19 UTC, merged