Added action classes, modified getAvailableActions method
htmlacademy-yii/796623-task-force-1 pull request #5
Opened 2020-11-05 18:49 UTC by likable

2020-11-06 12:33 UTC, andrewverner requested changes

2020-11-06 12:33 UTC, andrewverner commented on src/BusinessLogic/AbstractAction.php
> +    abstract protected function checkRights(int $user_id, int $customer_id, int $executor_id);
Имена переменных в нотации `studlyCase`

2020-11-06 12:33 UTC, andrewverner commented on src/BusinessLogic/CancelAction.php
> +        return ($user_id === $customer_id) ? true : false;
Тут достаточно будет написать так:

```php
return $userId === $customerId;
```

В остальных методах так же

2020-11-06 12:33 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +    const ACTION_CANCEL = 'CancelAction';
Лучше так:

```php
const ACTION_CANCEL = CancelAction::class;
```

Только обрати внимание, что CancelAction::class - строка с полным путём к классу `src\BusinessLogic\CancelAction`

2020-11-06 12:33 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +        $this->available_actions_map = [
Много лишней логики в конструкторе. Если ты создашь несколько экземпляров заданий, то разница у них будет только в идентификаторах исполнителя и заказчика. Остальные же данные будут у всех одинаковые. Значит их лучше вынести в константы, а не присваивать в приватные свойства в конструкторе

2020-11-06 12:33 UTC, andrewverner commented on src/BusinessLogic/Task.php
> +        return null;
Сложная логика и большая вложенность циклов и условий, от которой можно избавиться:

```php
const AVAILABLE_ACTIONS_MAP = [
    self::STATUS_NEW => [CancelAction::class, InWorkAction::class],
    //...
];

public function getAvailableActions(string $status, int $userId): ?AbstractAction
{
    if (!isset(self::AVAILABLE_ACTIONS_MAP[$status])) {
        return;
    }

    return array_filter(self::AVAILABLE_ACTIONS_MAP[$status], function ($action) use ($userId) {
        return $action::checkRights($userId, $this->customerId, $this->executorId);
    });
}
```

2020-11-11 18:12 UTC, likable commented on src/BusinessLogic/AbstractAction.php
> +    abstract protected function checkRights(int $user_id, int $customer_id, int $executor_id);
Это нужно для удобства разработки? Я не нашёл в PSR-12 рекомендаций на этот счёт, а в PSR-1 сказано, что можно использовать любой вариант написания (пункт 4.2).

2020-11-11 18:26 UTC, likable commented on src/BusinessLogic/Task.php
> +        $this->available_actions_map = [
Я так и хотел сделать, только оказалось, что свойствам и константам нельзя присвоить объект в качестве значения по умолчанию. Другого способа я не нашёл, но если можно сделать как-то получше, то расскажи мне. )

2020-11-11 20:10 UTC, likable commented on src/BusinessLogic/Task.php
> +        return null;
Смысл понятен, но такую конструкцию можно только на большом опыте соорудить. )
Я немного переписал метод и в таком варианте объекты классов-действий будут каждый раз создаваться заново при вызове этого метода. Вариант с созданием объектов внутри класса получится только если использовать свойство $availableActionsMap вместо константы AVAILABLE_ACTIONS_MAP (то, что я закомментировал).

2020-11-14 15:42 UTC, andrewverner commented on src/BusinessLogic/AbstractAction.php
> +    abstract protected function checkRights(int $user_id, int $customer_id, int $executor_id);
Это не требования, а рекомендации. `snake_case` используется очень редко в "особых" случаях

2020-11-14 17:59 UTC, merged